HS4_BlogProject.Presentation/Areas/Admin/Controllers/GenreController.cs
using HS4_BlogProject.Application.Models.DTOs;
using HS4_BlogProject.Application.Services.GenreSerivce;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HS4_BlogProject.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;

        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }

        // Genre List
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _genreService.GetGenres());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateGenreDTO model)
        {
            if (ModelState.IsValid)
            {
                _genreService.Create(model);
            }

            return RedirectToAction("Index");
        }
               
        public async Task<IActionResult> Update(int id)
        {
            // id ile Genre seçilir           
            return View(await _genreService.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateGenreDTO model)
        {
            // seçilen Genre Edit edildikten sonra veritabanında güncellenmek için gönderilir.
            await _genreService.Update(model);

            return RedirectToAction("Index"); 
        }
         
        public async Task<IActionResult> Delete(int id)
        {
            await _genreService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

HS4_BlogProject.Presentation/Areas/Admin/Views/Genre/Create.cshtml
@model CreateGenreDTO
@{
    ViewData["Title"] = "Create";
}


<div class="row ml-2 mt-2 mr-2">
    <div class="col-sm-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create Genre</h3>
            </div>
            <form asp-area="Admin" asp-controller="Genre" asp-action="Create" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input class="form-control" placeholder="Genre Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <a asp-action="List" class="btn btn-dark btn-sm mr-2 float-end">Back To List</a>
                    <input type="submit" class="btn btn-primary btn-sm float-end mr-2" value="Submit" />
                </div>
            </form>
        </div>
    </div>
</div>


HS4_BlogProject.Presentation/Areas/Admin/Views/Genre/Index.cshtml
@model List<GenreVM>
@{
    ViewData["Title"] = "List";
   
}

<div class="row ml-2 mt-2 mr-2">
    <div class="col-sm-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">List of Genre</h3>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>
                                    <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Update</a>
                                </td>
                                <td>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a asp-action="Create" class="btn btn-block btn-dark">Create Genre</a>
            </div>
        </div>
    </div>
</div>



HS4_BlogProject.Presentation/Areas/Admin/Views/Genre/Update.cshtml
@model UpdateGenreDTO
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row ml-2 mt-2 mr-2">
    <div class="col-sm-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Update Genre</h3>
            </div>
            <form asp-action="Update">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input class="form-control" placeholder="Genre Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <a asp-action="List" class="btn btn-dark btn-sm mr-2 float-end">Back To List</a>
                    <input type="submit" class="btn btn-primary btn-sm float-end mr-2" value="Submit" />
                </div>
            </form>
        </div>
    </div>
</div>
